source 'https://rubygems.org'

gem 'berkshelf'

group :integration do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
end

group :release do
  gem 'stove', '~> 1.1.2'
end

group :development do
  gem 'strainer', '~> 3.3.0'
  gem 'rubocop', '~> 0.18'
  gem 'foodcritic', '~> 3.0.0'
  gem 'chefspec', '~> 3.2'
  gem 'serverspec', '~> 0.14.2'
  gem 'guard', '~> 1.8'
  gem 'guard-rubocop', '~> 0.2'
  gem 'guard-foodcritic', '~> 1.0'
  gem 'guard-kitchen', '~> 0.0'
  gem 'guard-rspec', '~> 3.0'
end
